import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { cookies } from "next/headers";
import { NavBar } from "@/components/nav-bar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const theme = cookieStore.get("theme");
	const className = theme?.value && theme.value !== "system" ? theme.value : "";

	return (
		<html lang="en" className={className} style={{ colorScheme: className }}>
			<body className="antialiased flex flex-col min-h-screen items-center">
				<ThemeProvider
					attribute="class"
					defaultTheme={theme?.value || "system"}
					enableSystem
					disableTransitionOnChange
				>
					<NavBar className="container px-6" />
					<main className="container px-6">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
