/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCareerRouteImport } from './routes/admin/career'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminWorkRouteImport } from './routes/admin/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCareerRoute = AdminCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWorkRoute = AdminWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/career': typeof AdminCareerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/work': typeof AdminWorkRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/work': typeof AdminWorkRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/career': typeof AdminCareerRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/work': typeof AdminWorkRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/career'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/site'
    | '/admin/work'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/career'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/site'
    | '/admin/work'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/career'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/site'
    | '/admin/work'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/career': {
      id: '/admin/career'
      path: '/career'
      fullPath: '/admin/career'
      preLoaderRoute: typeof AdminCareerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/work': {
      id: '/admin/work'
      path: '/work'
      fullPath: '/admin/work'
      preLoaderRoute: typeof AdminWorkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCareerRoute: typeof AdminCareerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminWorkRoute: typeof AdminWorkRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCareerRoute: AdminCareerRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminWorkRoute: AdminWorkRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
